services:
  - type: web
    name: voiceops-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ELASTICSEARCH_URL
        sync: false
      - key: ELASTICSEARCH_API_KEY
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: LLM_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: JIRA_DOMAIN
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: JIRA_PROJECT_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
